# Generated by Django 2.0 on 2017-12-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=64)),
                ('drive', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('relpath', models.CharField(max_length=200)),
                ('stat_hash', models.BigIntegerField(null=True)),
                ('first_seen', models.DateTimeField(null=True)),
                ('verified_on', models.DateTimeField(null=True)),
                ('content_container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exo.ContentContainer')),
            ],
        ),
        migrations.CreateModel(
            name='ContentKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32)),
                ('sha2', models.CharField(max_length=64)),
                ('content_size', models.IntegerField()),
                ('resiliency', models.IntegerField(choices=[(1, 'Temporary'), (2, 'Sentimental'), (3, 'Destroy'), (4, 'Limited')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='exo.ContentSignature')),
                ('orientation', models.IntegerField(choices=[(90, '90 CW'), (270, '90 CCW'), (0, 'None'), (180, '180')], null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('taken_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('contentkey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exo.ContentKey')),
            ],
            bases=('exo.contentkey',),
        ),
        migrations.CreateModel(
            name='TransformedPicture',
            fields=[
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='exo.ContentSignature')),
                ('request_width', models.IntegerField(null=True)),
                ('request_height', models.IntegerField(null=True)),
                ('request_rotation', models.IntegerField(null=True)),
                ('result_width', models.IntegerField(null=True)),
                ('result_height', models.IntegerField(null=True)),
                ('result_rotation', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentsignature',
            name='content_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exo.ContentKey'),
        ),
        migrations.AddField(
            model_name='contentsignature',
            name='derived_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exo.ContentSignature'),
        ),
        migrations.AddField(
            model_name='contentsignature',
            name='tags',
            field=models.ManyToManyField(to='exo.Tag2'),
        ),
        migrations.AddField(
            model_name='contentkey',
            name='canonical',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exo.ContentSignature'),
        ),
        migrations.AddField(
            model_name='contentinstance',
            name='content_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exo.ContentSignature'),
        ),
        migrations.AlterUniqueTogether(
            name='contentcontainer',
            unique_together={('server', 'drive', 'path')},
        ),
        migrations.AddField(
            model_name='redirect',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exo.ContentKey'),
        ),
    ]
